import '../entities/duel_final_result.dart';
import '../entities/duel_invite.dart';
import '../entities/duel_invite_outcome.dart';
import '../entities/duel_opponent_answered_event.dart';
import '../entities/duel_question_event.dart';
import '../entities/duel_question_result.dart';
import '../entities/duel_started_info.dart';

/// Real-time duel signaling over a WebSocket connection — invites,
/// accept/decline, and (once accepted) the synchronized question-by-
/// question game itself.
abstract interface class DuelRepository {
  /// Fires whenever the WebSocket connection state changes.
  Stream<bool> get connectionStatus;

  /// Fires when someone challenges the current user to a duel.
  Stream<DuelInvite> get incomingInvites;

  /// Fires when an invite THIS device sent is accepted/declined/expires.
  Stream<DuelInviteOutcome> get outgoingInviteOutcomes;

  /// Fires for both players right after an invite is accepted.
  Stream<DuelStartedInfo> get duelStarted;

  /// Fires whenever the server pushes the current question.
  Stream<DuelQuestionEvent> get duelQuestion;

  /// Fires when the opponent locks in an answer for the current question.
  Stream<DuelOpponentAnsweredEvent> get opponentAnswered;

  /// Fires once both sides have answered (or timed out) a question.
  Stream<DuelQuestionResult> get duelQuestionResult;

  /// Fires once the duel is over.
  Stream<DuelFinalResult> get duelFinished;

  /// Opens the WebSocket connection (no-op if already connected).
  Future<void> connect();

  void disconnect();

  /// Sends a duel challenge. [clientInviteId] is generated by the
  /// caller so the eventual accept/decline/expire event can be matched
  /// back to this specific call (the server's own invite id isn't known
  /// until the connection acknowledges it).
  void sendInvite({
    required String toUserId,
    required int categoryId,
    required String clientInviteId,
  });

  /// Accepts or declines an invite from [incomingInvites].
  void respondToInvite({required String inviteId, required bool accept});

  /// Submits (or auto-submits `null` on timeout) an answer for the
  /// current question of an active duel.
  void submitAnswer({
    required String duelId,
    required int questionIndex,
    required int? selectedOption,
  });
}
